project:
  type: website
  output-dir: _site

website:
  title: "長崎大学 | 水圏植物生態学研究室"
  favicon: "assets/favicon.ico"
  description: "研究室HP"
  google-analytics: "G-4H79Y0YFP4"
  sidebar:
    style: "docked"
    search: true
    logo: "assets/images/logo001.png"
    contents:
      - text: "ホーム | Home"
        href: index.qmd
      
      - section: "ラボについて | About"
        contents:
        - about/current.qmd
        - about/alumni.qmd

      - section: "研究 | Research"
        contents:
          - research/index.qmd
          
      - text: "論文集 | Publications"
        href: papers.qmd
      
      - text: "連絡先 | Contact"
        href: contact.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    highlight-style:
      light: github
      dark: monokai
    toc: true
    lang: ja