---
title: "研究室メンバー"
---

### Gregory N. Nishihara (教授)
福島国際研究教育機構藻類応用生態学・ブルーイノベーション研究ユニット・サブユニットリーダー,
鹿児島大学連合農学研究科（2004 PhD）, University of Hawaii at Manoa (1996 BSc)。
2018 Marine Pew Fellow, 詳細は researchmap へ <a class="outlink" href="https://researchmap.jp/nagaremo">https://researchmap.jp/nagaremo</a>

### ROCKY Mehedi (メヘンディ) - 特任研究員 (PD)
私は、海洋微生物学および生態学、分子生物学、ゲノミクス、メタゲノミクスを専門としており、特に海洋大型植物（海草や海藻など）に焦点を当てています。 研究テーマとしては、海洋大型植物による炭素隔離、特にブルーカーボンとしての貯蔵機能に関心を持っています。 現在は、海草・海藻藻場におけるCO₂濃度のロガーによる評価と測定に取り組んでいます。 また、プラスチックごみが海洋大型植物に及ぼす影響、特にそれが沿岸生態系における生物地球化学的プロセスにどのような変化をもたらすかにも強い関心を持っています。

### 日野出 賢二郎 - 特任研究員 (PD)
調整中

### MALDINI Alifro (アリフ) - 博士後期課程 (D2)
海洋ゴミは、アマモの生長と生産性に影響を与えると考えられます。 そのため、海洋ゴミがアマモ場の生産量にどのように影響するかを理解し、アマモ場の炭素吸収能力に影響を与える要因を明らかにすることが目的です。
      
### 小坂 威博 - 博士後期課程 (D2)
炭酸カルシウムを主成分とする特殊なセラミックによる沿岸生態系への影響を評価します。 このセラミックは底質に直接作用するため、特にアマモのように根を張る海草はこの影響を受けると考えられます。 この技術が純一次生産量を向上させることで、ブルーカーボンへの貢献も期待できます。
      
### 青田 智之 - 海洋環境科学コース (D1)
海藻や海草の群落（藻場）は、魚類を含むさまざまな海洋生物に生息地を提供しています。 藻場の構造は、沿岸生態系における生息地の形成に寄与する重要な要因です。 現在、私は五島列島の有川湾において、大型藻類群集の構造と魚類群集の多様性との関連について研究しています。 
    
### 膳場 智幸 - 海洋生産管理学コース (D1)
調整中

### 野田勉 - 海洋生産管理学コース (D1)
調整中

### 河田優人 - 海洋生産管理学コース (D1)
調整中

### Maquirang, Jean Rose H. - 海洋生産管理学コース (M2)
ブルーカーボン生態系としての海藻（*Cladosiphon okaramanus*）養殖の可能性に関する研究は、ほとんど未開拓のままです。 そのため、私の研究の焦点は、海藻養殖による炭素隔離のダイナミクスと気候変動緩和への貢献を理解することにあります。

### 安斎 輝 - 海洋生産管理学コース (M2)
藻場は多くの二酸化炭素を吸収し、その一部を溶存態有機炭素(DOC)として放出しています。藻場のDOC動態を理解することはブルーカーボンを理解するうえで非常に重要です。 本研究では様々な植生の藻場のDOCの量、組成について研究を行い、植生の違いによってDOCの量、組成に違いがあるのかを明らかにすることを目的としています。

### 高島 望 - 海洋生産管理学コース (M2)
地下環境に埋没した海洋ごみが、アマモの生活史や藻場の拡大に及ぼす影響について研究しています。

### 植村 友香 - 海洋生物科学コース (M1)
堆積物に存在するプラスチックごみが堆積物中のＴＯＣにどのような影響を及ぼすかを研究しています。

### 木村 穂高 - 海洋生物科学コース (M1)
海洋ゴミの蓄積位置とその環境要因について調査しています。

### 加藤 大智 - 海洋環境科学コース (M1)
堆積物中の海藻バイオマス量とTOC・eDNAは比例するかどうかを研究しています。 未定

### 田中 瑛大- 海洋 (B4)
調整中

### 中西 洸- 海洋 (B4)
調整中

### 中辻 吉郎 - 海洋 (B4)
調整中


## 卒業生

* **植村 友香** - 2026 (BS) 
* **木村 穂高** - 2026 (BS) 
* **加藤 大智** - 2026 (BS) 
* **青田　智之** - 2026 (MS)
* **小林 大瞬** - 2026 (MS)
* **Becerra, Nathalia** - 2025 (ERASMUS 交換留学生)
* **Maldini, Alifro** - 2025 (MS)
* **安齋 輝** - 2025 (BS)
* **高島 望** - 2025 (BS)
* **浦沢 宗季** - 2024 (BS)
* **青田 智之** - 2024 (BS)
* **小林 大瞬** - 2024 (BS)
* **立石 裕人** - 2022 (BS), 2024 (MS)
* **松室 重孝** - 2022 (BS), 2024 (MS)
* **我部 山真** - 2022 (BS), 2024 (MS)
* **谷前 進一郎** - 2021 (BS), 2023 (MS)
* **須田 龍生** - 2023 (BS)
* **深瀬 叶真** - 2023 (BS)
* **山羽 香穂** - 2023 (BS), 2025 (MS)
* **浦江 壮志** - 2020 (BS), 2022 (MS)
* **磯田 朱莉** - 2021 (BS)
* **當山 健斗** - 2021 (BS)
* **日野出 賢二郎** - 2021 (PhD)
* **井上 幸男** - 2017 (MS), 2020 (PhD)
* **紙崎 星美** - 2018 (BS), 2020 (MS)
* **Belleza, Dominic** - 2020 (MS), 2023 (PhD)
* **日高 幹也** - 2020 (BS)
* **大崎 幸一** - 2019 (MS)
* **松田 悠平** - 2019 (BS), 2021 (MS)
* **畑田 菜緒** - 2019 (BS)
* **河手 梓** - 2019 (BS), 2021 (MS)
* **松尾 彩音** - 2018 (MS)
* **才津 真子** - 2015 (BS), 2017 (MS)
* **小島 康平** - 2016 (BS)
* **古賀 愛梨沙** - 2015 (BS)
* **李 雪娜 (Li, Xuena)** - 2015 (Shanghai Ocean University 交換留学生)
* **木村 竜太郎** - 2012 (BS), 2014 (MS)
* **岡村 琴江** - 2014 (BS)
* **山田 千瑞** - 2012 (BS)