---
title: "卒業生・修了生 | Alumni"
---

* **植村 友香 | Uemura Yuka** - 2026 (BS) 
* **木村 穂高 | Kimura Hotaka** - 2026 (BS) 
* **加藤 大智 | Kato Taichi** - 2026 (BS) 
* **Becerra Nathalia** - 2025 (AIMS ERASMUS 交換留学生)
* **Maldini Alifro** - 2025 (MS)
* **安齋 輝 | Ansai Hikaru** - 2025 (BS)
* **高島 望 | Takashima Nozomu** - 2025 (BS)
* **浦沢 宗季 | Urasawa Toshiki** - 2024 (BS)
* **青田 智之 | Aota Tomoyuki** - 2024 (BS), 2026 (MS)
* **小林 大瞬 | Kobayashi Taishun** - 2024 (BS), 2026 (MS)
* **立石 裕人 | Tateishi Hiroto** - 2022 (BS), 2024 (MS)
* **松室 重孝 | Matsumuro Shigetaka** - 2022 (BS), 2024 (MS)
* **我部山 真 |Kabeyama Makoto** - 2022 (BS), 2024 (MS)
* **谷前 進一郎 | Tanimae Shin-ichiro** - 2021 (BS), 2023 (MS)
* **須田 龍生 | Suda Ryusei** - 2023 (BS)
* **深瀬 叶真 | Fukase Toma** - 2023 (BS)
* **山羽 香穂 | Yamaha Kaho** - 2023 (BS), 2025 (MS)
* **浦江 壮志** - 2020 (BS), 2022 (MS)
* **磯田 朱莉 | Isoda Akari** - 2021 (BS)
* **當山 健斗 | Toyama Kento** - 2021 (BS)
* **日野出 賢二郎 | Hinode Kenjiro** - 2021 (PhD)
* **井上 幸男 | Inoue Yukio** - 2017 (MS), 2020 (PhD)
* **紙崎 星美 | Kamisaki Hoshimi** - 2018 (BS), 2020 (MS)
* **Belleza Dominic** - 2020 (MS), 2023 (PhD)
* **日高 幹也 | Hidaka Mikiya** - 2020 (BS)
* **大崎 幸一 | Osaki Koichi** - 2019 (MS)
* **松田 悠平 | Matsuda Yuhei** - 2019 (BS), 2021 (MS)
* **畑田 菜緒 | Hatata Nao** - 2019 (BS)
* **河手 梓 | Kawate Azusa** - 2019 (BS), 2021 (MS)
* **松尾 彩音 |Matsuo Ayane** - 2018 (MS)
* **才津 真子 | Saitsu Mako** - 2015 (BS), 2017 (MS)
* **小島 康平 | Kojima Kohei** - 2016 (BS)
* **古賀 愛梨沙 | Koga Arisa** - 2015 (BS)
* **李 雪娜 | Li Xuena** - 2015 (Shanghai Ocean University 交換留学生)
* **木村 竜太郎 | Kimura Ryutaro** - 2012 (BS), 2014 (MS)
* **岡村 琴江 | Okamura Kotoe** - 2014 (BS)
* **山田 千瑞 | Yamada Chizuru** - 2012 (BS)
